development:
  adapter: mysql
  database: taskflakes_development
  host: localhost
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql
  database: taskflakes_test
  host: localhost
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql
  database: taskflakes
  host: localhost
  username: root
  password:
  encoding: utf8

test_sqlite3:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000


